### ISSUE TITLE
Job cancelation on verticle undeployment

### ISSUE THREAD

**Issue by oleg-kiriyenko** [vert-x3/vertx-lang-kotlin#189]
### Questions

Jobs are not canceled when verticle was undeployed

### Version

4.0.2

### Do you have a reproducer?

```kotlin
package com.example.starter

import io.vertx.core.Vertx
import io.vertx.kotlin.coroutines.CoroutineVerticle
import io.vertx.kotlin.coroutines.await
import io.vertx.kotlin.coroutines.dispatcher
import kotlinx.coroutines.*

class MainVerticle : CoroutineVerticle() {

  override suspend fun start() {
    val httpServerFuture = vertx
      .createHttpServer()
      .requestHandler { req ->
        req.response()
          .putHeader("content-type", "text/plain")
          .end("Hello from Vert.x!")
      }
      .listen(8888);

    val httpServer = httpServerFuture.await();
    println("HTTP server started on port 8888");

    val jobs = ArrayList<Job>();
    for (i in 1..2) {
      val job = launch {

        while (true) {
          println("job $i in ${Thread.currentThread().name} is active $isActive")
          delay(1000)
        }
      }
      jobs.add(job);
    }

    println("Started $isActive")

//    launch {
//      delay(5_000);
//      println("Cancel jobs")
//      jobs.forEach { job -> job.cancel() }
//    }

  }

  override suspend fun stop() {
    super.stop()
    println("Scope $isActive")
  }

}

fun main() {
  val vertx = Vertx.vertx();
  GlobalScope.launch(vertx.dispatcher()) {
    println("Global vertx scope ${Thread.currentThread().name}")
    val deploymentId = vertx.deployVerticle("com.example.starter.MainVerticle").await();
    delay(10_000);
    vertx.undeploy(deploymentId).await();
    println("Stopped 1");
    delay(2_000);
    vertx.close().await()
    println("Stopped 2");
  }
}
```

Output looks like this (after stopped 1 is shown we still get messages from launched coroutines):

```
Global vertx scope vert.x-eventloop-thread-0
HTTP server started on port 8888
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
Started true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
Scope true
Stopped 1
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true
job 1 in vert.x-eventloop-thread-1 is active true
job 2 in vert.x-eventloop-thread-1 is active true

Process finished with exit code 0
```

**Comment by vietj** [comment]
can you provide a PR with a test for this project ? then we would use it to fix the issue

**Comment by rgmz** [comment]
I will note, [there is a subtle but important distinction between](https://vertx.io/docs/vertx-lang-kotlin-coroutines/kotlin/#_coroutine_builders):
```kotlin
class MainVerticle : CoroutineVerticle() {

  override suspend fun start() {
```

and

```kotlin
class MainVerticle : CoroutineVerticle() {

  override suspend fun start(): Unit = coroutineScope {
```

I assumed the issue was the lack of the `coroutineScope` builder, but while writing a test for this I discovered that using `coroutineScope { }` causes the code to never proceed past this line -- the test eventually times out:
```kotlin
    val deploymentId = vertx.deployVerticle("com.example.starter.MainVerticle").await();
```

Output:
```
Starting jobs...
job 1 in vert.x-eventloop-thread-1 @coroutine#3 is active: isActive=true
job 2 in vert.x-eventloop-thread-1 @coroutine#4 is active: isActive=true
Verticle deployed
job 1 in vert.x-eventloop-thread-1 @coroutine#3 is active: isActive=true
job 2 in vert.x-eventloop-thread-1 @coroutine#4 is active: isActive=true
job 1 in vert.x-eventloop-thread-1 @coroutine#3 is active: isActive=true
job 2 in vert.x-eventloop-thread-1 @coroutine#4 is active: isActive=true
job 1 in vert.x-eventloop-thread-1 @coroutine#3 is active: isActive=true
... (repeats)

java.util.concurrent.TimeoutException
	at io.vertx.ext.unit.impl.TestContextImpl.lambda$run$1(TestContextImpl.java:79)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

@vietj Any idea why that would be the case? I created PR #200 for reference.

**Comment by rgmz** [comment]
**Follow-up:** the same appears true for non-Vertx usage, so perhaps there's something I'm missing. My initial assumption was that the jobs weren't being cancelled due to the lack of a `coroutineScope { }`, meaning the jobs weren't associated with the parent context.

```kotlin
package io.vertx.kotlin.coroutines.verticles

import kotlinx.coroutines.*
import kotlin.coroutines.CoroutineContext

class Verticle : CoroutineScope {
  override val coroutineContext: CoroutineContext = Job()

  val jobs: MutableList<Job> = mutableListOf()

  suspend fun start(): Unit = coroutineScope {
    println("Starting jobs...")
    for (i in 1..2) {
      val job = launch(Dispatchers.IO) {
        while (true) {
          println("job $i in ${Thread.currentThread().name} is active: isActive=$isActive")
          delay(1000)
        }
      }
      jobs.add(job)
    }

    println("Verticle deployed")
  }

  suspend fun stop() = coroutineScope {
    coroutineContext.cancel()
    println("Stopping verticle... coroutine job: isActive=$isActive")
  }

}

fun main() = runBlocking {
  println("Global vertx scope ${Thread.currentThread().name}")
  try {
    val verticle = Verticle()
    verticle.start()
    println("Verticle is started")
    delay(2_000)
    verticle.stop()
    println("Stopped 1")
  } finally {
    delay(2_000)
    this.cancel("Cancelling GlobalScope.launch { }")
    println("Stopped 2")
  }
}

```
