### ISSUE TITLE
Kotlin fixes

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-lang-kotlin#262]
- a contribution was reverted in circuit breaker that makes Kotlin compilation fail:

```
[INFO] --- kotlin:1.7.21:compile (default) @ vertx-lang-kotlin ---
[ERROR] /Users/julien/java/vertx-lang-kotlin/vertx-lang-kotlin/src/main/kotlin/io/vertx/kotlin/circuitbreaker/CircuitBreakerOptions.kt: (42, 72) One type argument expected for interface AsyncResult<T : Any!>
```

- the test `test Coroutine execution not always performed with dispatch` fails, it tries to connect to https://example.com

```
Exception in thread "vert.x-eventloop-thread-0 @coroutine#4" io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: example.com/127.0.0.1:443
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineId(4), "coroutine#4":StandaloneCoroutine{Cancelling}@792a78ab, ContextCoroutineDispatcher@5ad8c806]
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by tsegismont** [comment]
Fixed by #263 and https://github.com/vert-x3/vertx-circuit-breaker/pull/73
